env:
- REPO=skeenan947/alexa-srvbc
services:
- docker
install:
- export DOCKER_TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest";
  else echo $TRAVIS_BRANCH; fi`
- RAILS_ENV=test docker-compose up -d --build
- bundle install
- docker run -d -p 127.0.0.1:9999:6379 redis:alpine
script:
- REDIS_URL=redis://localhost:9999 bundle exec rake test
- docker ps | grep -q alexa-srvbc
- sleep 5
- curl -s http://localhost:5000/health
- docker logs alexa-srvbc
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest";
  else echo $TRAVIS_BRANCH; fi`
- docker-compose push web
- docker tag $REPO:$TAG $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker tag $REPO:$TAG $REPO:$TRAVIS_COMMIT
- docker push $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO:$TRAVIS_COMMIT
addons:
  ssh_known_hosts: skeenan.net
deploy:
  provider: script
  script: scripts/deploy.sh skeenan.net
  skip_cleanup: true
  on:
    branch: master
