env:
- REPO=skeenan947/alexa-srvbc
services:
- docker
install:
- RAILS_ENV=test docker-compose up -d --build
- bundle install
script:
- docker ps | grep -q alexa-srvbc
- sleep 5
- curl -s http://localhost:5000/health
- bundle exec rake test
- docker logs alexa-srvbc
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker tag alexa-srvbc $REPO:$TAG
- docker tag alexa-srvbc $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker tag alexa-srvbc $REPO:$TRAVIS_COMMIT
- docker push $REPO:$TAG
- docker push $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO:$TRAVIS_COMMIT
addons:
  ssh_known_hosts: skeenan.net
deploy:
  provider: script
  script: scripts/deploy.sh skeenan.net
  skip_cleanup: true
  on:
    branch: master
