env:
- REPO=skeenan947/alexa-srvbc
services:
- docker
install:
- docker build -f Dockerfile -t $REPO:$TRAVIS_COMMIT .
- docker run -e RAILS_ENV=test -td -p 127.0.0.1:5000:5000 --name alexa-srvbc $REPO:$TRAVIS_COMMIT
- bundle install
script:
- docker ps | grep -q alexa-srvbc
- sleep 5
- curl -s http://localhost:5000/health
- bundle exec rake spec
- docker logs alexa-srvbc
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG
- docker tag $REPO:$TRAVIS_COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO:$TAG
- docker push $REPO:travis-$TRAVIS_BUILD_NUMBER
addons:
  ssh_known_hosts: skeenan.net
deploy:
  provider: script
  script: scripts/deploy.sh skeenan.net
  skip_cleanup: true
  on:
    branch: master
