env:
<<<<<<< HEAD
- REPO=skeenan947/alexa-srvbc
=======
- env REPO=skeenan947/alexa-srvbc
>>>>>>> 9c522b2e524ab450e4e408297d7c9756b9dc32c8
services:
- docker
install:
- docker build -f Dockerfile -t $REPO:$TRAVIS_COMMIT .
- docker run -d -p 127.0.0.1:4567:4567 --name alexa-srvbc $REPO
script:
- docker ps | grep -q alexa-srvbc
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
<<<<<<< HEAD
addons:
  ssh_known_hosts: skeenan.net
deploy:
  provider: script
  script: ./deploy.sh skeenan.net
  on:
    branch: master
=======
before_install:
- test -d ~/.ssh || mkdir ~/.ssh
- openssl aes-256-cbc -K $encrypted_b293f50235e4_key -iv $encrypted_b293f50235e4_iv
  -in id_travis.enc -out ~/.ssh/id_travis -d
- test "$TRAVIS_BRANCH" == "master" && ssh skeenan@skeenan.net docker run -d -p127.0.0.1:9899:4567 $REPO:$TAG || true
>>>>>>> 9c522b2e524ab450e4e408297d7c9756b9dc32c8
