env:
- REPO=skeenan947/alexa-srvbc
services:
- docker
install:
- docker build -f Dockerfile -t $REPO:$TRAVIS_COMMIT .
- docker run -d -p 127.0.0.1:5000:5000 --name alexa-srvbc $REPO:$TRAVIS_COMMIT
script:
- docker ps | grep -q alexa-srvbc
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
addons:
  ssh_known_hosts: skeenan.net
deploy:
  provider: script
  script: scripts/deploy.sh skeenan.net
  skip_cleanup: true
  on:
    branch: master
